name: Deploy Website
on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Data Folder and Config File
        run: |
          mkdir -p data
          # 這裡會從你設定的 Secret 抓取 API_KEY，產出一個 json 檔
          echo '{"API_KEY": "${{ secrets.API_KEY }}"}' > data/config.json

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # 你的網頁根目錄
